"""reczna poprawka odpowiedzi

Revision ID: eaa2533b6a34
Revises: fd7f319df3bd
Create Date: 2026-09-15 06:29:34.287555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa2533b6a34'
down_revision: Union[str, None] = 'fd7f319df3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('edited_text', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'edited_text')
    # ### end Alembic commands ###
